### ISSUE TITLE
For HTML, convert divs to paragraphs

### ISSUE THREAD

**Issue by kylegibson** [PolicyStat/htmltreediff#12]

**Comment by kylegibson** [comment]
Updating test cases is proving difficult

```python
ipdb> print minidom_tostring(parse_lxml_dom(xml, strict_xml=True))
<p><h1>one</h1>tail</p>
ipdb> print minidom_tostring(parse_lxml_dom(xml, strict_xml=False))
<html><body><p/><h1>one</h1>tail</body></html>
```

**Comment by kylegibson** [comment]
```python
from xml.dom.pulldom import SAX2DOM
import lxml.html
import lxml.etree
import lxml.sax


def foo(xml, func):
    tree = func(xml)
    handler = SAX2DOM()
    lxml.sax.saxify(tree, handler)
    return handler.document

>>> foo('<p><h1>one</h1>tail</p>', lxml.html.document_fromstring).toxml()
'<?xml version="1.0" ?><html><body><p/><h1>one</h1>tail</body></html>'
>>> foo('<p><h1>one</h1>tail</p>', lxml.etree.fromstring).toxml()
'<?xml version="1.0" ?><p><h1>one</h1>tail</p>'
```

It seems that `lxml.html.document_fromstring` can't handle paragraphs containing block level elements, and as a consequence, many tests are busted.

**Comment by kylegibson** [comment]
The problem now with updating test cases is `test_cases_sanity` in `tests.py`. 

```
FAIL: test_cases_sanity - text normalization
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kyle/dev/htmltreediff/.tox/py26/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/kyle/dev/htmltreediff/htmltreediff/tests.py", line 1356, in test
    case.target_changes,
  File "/home/kyle/dev/htmltreediff/htmltreediff/tests.py", line 1229, in assert_strip_changes
    assert_html_equal(old_html, strip_changes_old(changes))
  File "/home/kyle/dev/htmltreediff/htmltreediff/tests.py", line 1214, in assert_html_equal
    b_html,
AssertionError: These html documents are not equal:
'<p>first <em>middle</em> last</p>'
====
'<div>first <em>middle</em> last</div>'
```

It means even the before/after states have to be updated to divs, not just the changes. 

What `test_cases_sanity` does is remove the del/ins tags and verifies that it matches the inputs. Since we're converting paragraphs to divs, any input with a paragraph will become a div. That output won't match the input. But if we update the input too, it changes the test.
