### ISSUE TITLE
Unwrapped div appears as content change

### ISSUE THREAD

**Issue by kylegibson-rldatix** [PolicyStat/htmltreediff#2]
```
FAIL: htmltreediff.test_html.test_unwrap_div_shows_as_content_change
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/env/src/nose/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/home/vagrant/PolicyStat/htmltreediff/htmltreediff/test_html.py", line 141, in test_unwrap_div_shows_as_content_change
    '<ul><li>Foo bar</li></ul>'
AssertionError: '<ul><li><del><div>Foo bar</div></del><ins>Foo bar</ins></li></ul>' != '<ul><li>Foo bar</li></ul>'
```

**Comment by kylegibson** [comment]
Hm. So there's no precedent in the code base for a change like this. Most of the code is written to be non-html specific. If we were to code this specific to div's it would need to be in the `html` module. But by then, it seems too late to intercept the change without some additional pre or post processing, thus making the diffing slower than it already is. Boo.
